name: Telegram Push
on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.19.1
      # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
      - name: Generate Environment Variables File for Production
        run: |
          echo "BOT_ID=$BOT_ID" >> .env
          echo "BOT_TOKEN=$BOT_TOKEN" >> .env
          echo "CALENDAR_ID=$CALENDAR_ID" >> .env
          echo "HOLIDAY_CALENDAR_ID=$HOLIDAY_CALENDAR_ID" >> .env
          echo "GOOGLE_PRIVATE_KEY=$GOOGLE_PRIVATE_KEY" >> .env
          echo "GOOGLE_CLIENT_EMAIL=$GOOGLE_CLIENT_EMAIL" >> .env
          echo "GOOGLE_PROJECT_NUMBER=$GOOGLE_PROJECT_NUMBER" >> .env
        env:
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          HOLIDAY_CALENDAR_ID: ${{ secrets.HOLIDAY_CALENDAR_ID }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PROJECT_NUMBER: ${{ secrets.GOOGLE_PROJECT_NUMBER }}

      - run: npm install
      - run: npm run start
